/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),r=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}};
r("Symbol",function(a){if(a)return a;var b=function(f,l){this.ea=f;q(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.ea};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&q(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},w=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
r("WeakMap",function(a){function b(){}function c(h){var k=typeof h;return"object"===k&&null!==h||"function"===k}function d(h){if(!w(h,f)){var k=new b;q(h,f,{value:k})}}function e(h){var k=Object[h];k&&(Object[h]=function(m){if(m instanceof b)return m;Object.isExtensible(m)&&d(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),k=Object.seal({}),m=new a([[h,2],[k,3]]);if(2!=m.get(h)||3!=m.get(k))return!1;m.delete(h);m.set(k,4);return!m.has(h)&&4==m.get(k)}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,g=function(h){this.P=(l+=Math.random()+1).toString();if(h){h=v(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};g.prototype.set=function(h,k){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!w(h,f))throw Error("WeakMap key fail: "+h);h[f][this.P]=k;return this};g.prototype.get=function(h){return c(h)&&w(h,f)?h[f][this.P]:void 0};g.prototype.has=function(h){return c(h)&&w(h,f)&&w(h[f],this.P)};
g.prototype.delete=function(h){return c(h)&&w(h,f)&&w(h[f],this.P)?delete h[f][this.P]:!1};return g});
r("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(v([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var k=h.entries(),m=k.next();if(m.done||m.value[0]!=g||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!k.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(g){this.O={};this.C=f();
this.size=0;if(g){g=v(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=0===g?0:g;var k=d(this,g);k.list||(k.list=this.O[k.id]=[]);k.entry?k.entry.value=h:(k.entry={next:this.C,previous:this.C.previous,head:this.C,key:g,value:h},k.list.push(k.entry),this.C.previous.next=k.entry,this.C.previous=k.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.O[g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.O={};this.C=this.C.previous=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,
function(g){return g.value})};c.prototype.forEach=function(g,h){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,g.call(h,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var k=h&&typeof h;"object"==k||"function"==k?b.has(h)?k=b.get(h):(k=""+ ++l,b.set(h,k)):k="p_"+h;var m=g.O[k];if(m&&w(g.O,k))for(g=0;g<m.length;g++){var p=m[g];if(h!==h&&p.key!==p.key||h===p.key)return{id:k,list:m,index:g,entry:p}}return{id:k,list:m,index:-1,entry:void 0}},e=function(g,
h){var k=g.C;return da(function(){if(k){for(;k.head!=g.C;)k=k.previous;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};k=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.previous=g.next=g.head=g},l=0;return c});var ea=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
r("Array.prototype.values",function(a){return a?a:function(){return ea(this,function(b,c){return c})}});r("Array.prototype.keys",function(a){return a?a:function(){return ea(this,function(b){return b})}});
r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var l=0;!(f=b.next()).done;)e.push(c.call(d,f.value,l++))}else for(f=b.length,l=0;l<f;l++)e.push(c.call(d,b[l],l));return e}});
var x=this||self,y=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},z=function(a){var b=y(a);return"array"==b||"object"==b&&"number"==typeof a.length},A=function(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ja=function(d,e,f){for(var l=Array(arguments.length-2),g=2;g<arguments.length;g++)l[g-2]=arguments[g];return b.prototype[e].apply(d,l)}},B=function(a){return a};function C(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,C);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}A(C,Error);C.prototype.name="CustomError";var D=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");C.call(this,c+a[d])};A(D,C);D.prototype.name="AssertionError";
var E=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new D(""+e,f||[]);},F=function(a,b,c){a||E("",null,b,Array.prototype.slice.call(arguments,2));return a},G=function(a,b){throw new D("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},H=function(a,b,c){"number"!==typeof a&&E("Expected number but got %s: %s.",[y(a),a],b,Array.prototype.slice.call(arguments,2));return a},fa=function(a,b,c){"string"!==typeof a&&E("Expected string but got %s: %s.",
[y(a),a],b,Array.prototype.slice.call(arguments,2))};var ha=/&/g,ia=/</g,ja=/>/g,ka=/"/g,la=/'/g,ma=/\x00/g,na=/[\x00&<>"']/;var I;var K=function(a,b){this.Y=a===J&&b||"";this.fa=oa};K.prototype.ca=!0;K.prototype.ba=function(){return this.Y};K.prototype.toString=function(){return"Const{"+this.Y+"}"};var pa=function(a){if(a instanceof K&&a.constructor===K&&a.fa===oa)return a.Y;G("expected object of type Const, got '"+a+"'");return"type_error:Const"},oa={},J={};var qa={},L=function(a,b,c){this.W=c===qa?a:"";this.aa=b;this.ca=this.ha=!0};L.prototype.ba=function(){return this.W.toString()};L.prototype.toString=function(){return this.W.toString()};
var ra=function(a){if(a instanceof L&&a.constructor===L)return a.W;G("expected object of type SafeHtml, got '"+a+"' of type "+y(a));return"type_error:SafeHtml"},ta=function(a){if(a instanceof L)return a;var b="object"==typeof a,c=null;b&&a.ha&&(c=a.aa);a=b&&a.ca?a.ba():String(a);na.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(ha,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(ia,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(ja,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(ka,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(la,
"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(ma,"&#0;")));return sa(a,c)},sa=function(a,b){if(void 0===I){var c=null;var d=x.trustedTypes;if(d&&d.createPolicy)try{c=d.createPolicy("goog#html",{createHTML:B,createScript:B,createScriptURL:B})}catch(e){x.console&&x.console.error(e.message)}I=c}a=(c=I)?c.createHTML(a):a;return new L(a,b,qa)},ua=new L(x.trustedTypes&&x.trustedTypes.emptyHTML||"",0,qa);var va=function(a,b,c){fa(pa(a),"must provide justification");F(!/^[\s\xa0]*$/.test(pa(a)),"must provide non-empty justification");return sa(b,c||null)};var wa={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},xa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=ra(ua);return!b.parentElement}),ya=function(a,b){if(xa())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=ra(b)};var Ba=function(a){return-1!=a.indexOf("&")?"document"in x?za(a):Aa(a):a},za=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=x.document.createElement("div");return a.replace(Ca,function(d,e){var f=b[d];if(f)return f;"#"==e.charAt(0)&&(e=Number("0"+e.substr(1)),isNaN(e)||(f=String.fromCharCode(e)));if(!f){f=va(new K(J,"Single HTML entity."),d+" ");if(c.tagName&&wa[c.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+c.tagName+
".");ya(c,f);f=c.firstChild.nodeValue.slice(0,-1)}return b[d]=f})},Aa=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:return"#"!=c.charAt(0)||(c=Number("0"+c.substr(1)),isNaN(c))?b:String.fromCharCode(c)}})},Ca=/&([^;\s<&]+);?/g;var Da=function(a){if(a.I&&"function"==typeof a.I)return a.I();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(z(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},Fa=function(a){if(a.V&&"function"==typeof a.V)return a.V();if(!a.I||"function"!=typeof a.I){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==
typeof Set&&a instanceof Set)){if(z(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}},Ga=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(z(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=Fa(a),e=Da(a),f=e.length,l=0;l<f;l++)b.call(c,e[l],d&&d[l],a)};var Ha=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Ia=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var M=function(a,b){this.B=this.J=this.G="";this.N=null;this.H=this.u="";this.o=this.ia=!1;if(a instanceof M){this.o=void 0!==b?b:a.o;Ja(this,a.G);var c=a.J;N(this);this.J=c;c=a.B;N(this);this.B=c;Ka(this,a.N);c=a.u;N(this);this.u=c;La(this,a.j.clone());a=a.H;N(this);this.H=a}else a&&(c=String(a).match(Ha))?(this.o=!!b,Ja(this,c[1]||"",!0),a=c[2]||"",N(this),this.J=O(a),a=c[3]||"",N(this),this.B=O(a,!0),Ka(this,c[4]),a=c[5]||"",N(this),this.u=O(a,!0),La(this,c[6]||"",!0),a=c[7]||"",N(this),this.H=
O(a)):(this.o=!!b,this.j=new P(null,this.o))};M.prototype.toString=function(){var a=[],b=this.G;b&&a.push(Q(b,Ma,!0),":");var c=this.B;if(c||"file"==b)a.push("//"),(b=this.J)&&a.push(Q(b,Ma,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.N,null!=c&&a.push(":",String(c));if(c=this.u)this.B&&"/"!=c.charAt(0)&&a.push("/"),a.push(Q(c,"/"==c.charAt(0)?Na:Oa,!0));(c=this.j.toString())&&a.push("?",c);(c=this.H)&&a.push("#",Q(c,Pa));return a.join("")};
M.prototype.resolve=function(a){var b=this.clone(),c=!!a.G;c?Ja(b,a.G):c=!!a.J;if(c){var d=a.J;N(b);b.J=d}else c=!!a.B;c?(d=a.B,N(b),b.B=d):c=null!=a.N;d=a.u;if(c)Ka(b,a.N);else if(c=!!a.u){if("/"!=d.charAt(0))if(this.B&&!this.u)d="/"+d;else{var e=b.u.lastIndexOf("/");-1!=e&&(d=b.u.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],l=0;l<e.length;){var g=e[l++];"."==g?d&&l==e.length&&f.push(""):".."==
g?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&l==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?(N(b),b.u=d):c=""!==a.j.toString();c?La(b,a.j.clone()):c=!!a.H;c&&(a=a.H,N(b),b.H=a);return b};M.prototype.clone=function(){return new M(this)};
var Ja=function(a,b,c){N(a);a.G=c?O(b,!0):b;a.G&&(a.G=a.G.replace(/:$/,""))},Ka=function(a,b){N(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.N=b}else a.N=null},La=function(a,b,c){N(a);b instanceof P?(a.j=b,a.j.X(a.o)):(c||(b=Q(b,Qa)),a.j=new P(b,a.o))};M.prototype.getQuery=function(){return this.j.toString()};M.prototype.removeParameter=function(a){N(this);this.j.remove(a);return this};var N=function(a){if(a.ia)throw Error("Tried to modify a read-only Uri");};
M.prototype.X=function(a){this.o=a;this.j&&this.j.X(a)};
var O=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Q=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Ra),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Ra=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ma=/[#\/\?@]/g,Oa=/[#\?:]/g,Na=/[#\?]/g,Qa=/[#\?@]/g,Pa=/#/g,P=function(a,b){this.i=this.g=null;this.l=a||null;this.o=!!b},R=function(a){a.g||(a.g=new Map,a.i=0,a.l&&Ia(a.l,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};P.prototype.add=function(a,b){R(this);this.l=null;a=S(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i=H(this.i)+1;return this};P.prototype.remove=function(a){R(this);a=S(this,a);return this.g.has(a)?(this.l=null,this.i=H(this.i)-this.g.get(a).length,this.g.delete(a)):!1};P.prototype.clear=function(){this.g=this.l=null;this.i=0};var Sa=function(a,b){R(a);b=S(a,b);return a.g.has(b)};n=P.prototype;
n.forEach=function(a,b){R(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};n.V=function(){R(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};n.I=function(a){R(this);var b=[];if("string"===typeof a)Sa(this,a)&&(b=b.concat(this.g.get(S(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};
n.set=function(a,b){R(this);this.l=null;a=S(this,a);Sa(this,a)&&(this.i=H(this.i)-this.g.get(a).length);this.g.set(a,[b]);this.i=H(this.i)+1;return this};n.get=function(a,b){if(!a)return b;a=this.I(a);return 0<a.length?String(a[0]):b};
n.toString=function(){if(this.l)return this.l;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.I(d);for(var f=0;f<d.length;f++){var l=e;""!==d[f]&&(l+="="+encodeURIComponent(String(d[f])));a.push(l)}}return this.l=a.join("&")};n.clone=function(){var a=new P;a.l=this.l;this.g&&(a.g=new Map(this.g),a.i=this.i);return a};var S=function(a,b){b=String(b);a.o&&(b=b.toLowerCase());return b};
P.prototype.X=function(a){a&&!this.o&&(R(this),this.l=null,this.g.forEach(function(b,c){var d=c.toLowerCase();if(c!=d&&(this.remove(c),this.remove(d),0<b.length)){this.l=null;c=this.g;var e=c.set;d=S(this,d);var f=b.length;if(0<f){for(var l=Array(f),g=0;g<f;g++)l[g]=b[g];f=l}else f=[];e.call(c,d,f);this.i=H(this.i)+b.length}},this));this.o=a};P.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)Ga(arguments[b],function(c,d){this.add(d,c)},this)};var Ta={la:!0},T=function(){throw Error("Do not instantiate directly");};T.prototype.T=null;T.prototype.getContent=function(){return this.content};T.prototype.toString=function(){return this.content};var U=function(){T.call(this)};A(U,T);U.prototype.Z=Ta;/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ua=function(a){var b=null!=a&&a.Z===Ta;b&&F(a.constructor===U);return b};var Va=function(a){if(null!=a)switch(a.T){case 1:return 1;case -1:return-1;case 0:return 0}return null},Za=function(a){return Ua(a)?a:a instanceof L?Wa(ra(a).toString(),a.aa):Wa(String(String(a)).replace(Xa,Ya),Va(a))},Wa=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.T=d);return c}}(U),$a={},V=function(a){if(Ua(a)){var b=String;a=a.getContent();a=String(a).replace(ab,"").replace(bb,"&lt;");b=b(a).replace(cb,Ya)}else b=String(a).replace(Xa,
Ya);return b},db={},eb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},Ya=function(a){return eb[a]},Xa=/[\x00\x22\x26\x27\x3c\x3e]/g,cb=/[\x00\x22\x27\x3c\x3e]/g,ab=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,bb=/</g;var W=function(a,b){this.text=a;this.type=b},fb=function(a,b){this.spans=a;this.type=b},gb="break case catch continue debugger default delete do else finally for function if in instanceof new return switch this throw try typeof var void while with false null undefined true abstract boolean byte char const double final float goto int long native short synchronized throws transient volatile class enum export extends import super implements interface let package private protected public static yield".split(" "),
hb=function(a,b){try{var c=new XMLHttpRequest;c.open("GET",a,!0);var d=!1;c.onreadystatechange=function(){d||4!=c.readyState||200!=c.status||(d=!0,b(c))};c.send()}catch(e){}},X={type:"html-tag",open:/^<\/?([-_a-zA-Z0-9]+)/,close:/^(\/?)>/,da:function(a,b){a.U=b[1].toUpperCase();return!0},S:function(a,b){""==b[1]&&("SCRIPT"==a.U?(a.A="js-code",a.L=null,a.R=ib):"STYLE"==a.U&&(a.A="css-code",a.L=null,a.R=jb));return!0}},kb=[{type:"html-comment",open:"\x3c!--",close:"--\x3e"},{type:"html-cdata",open:"<![CDATA[",
close:"]]\x3e"},{type:"html-doctype",open:"<!",close:">"},X,{type:"html-attribute-url",open:/^"(https?|\/\/)/,close:'"',escape:"\\",v:X},{type:"html-attribute-url",open:/^'(https?|\/\/)/,close:"'",escape:"\\",v:X},{type:"html-attribute-value",open:'"',close:'"',escape:"\\",v:X},{type:"html-attribute-value",open:"'",close:"'",escape:"\\",v:X},{type:"html-attribute-name",open:/(^[-_a-zA-Z0-9]+)/,close:"=",v:X}],ib=[{type:"js-comment",open:"//",K:!0},{type:"js-comment",open:"/*",close:"*/"},{type:"js-string",
open:'"',close:'"',escape:"\\",K:!0},{type:"js-regex",open:"/",close:"/",escape:"\\",K:!0},{open:/^\.[a-zA-Z_][a-zA-Z_0-9]*/,F:!0},{type:"js-keyword",open:/^[a-zA-Z_][a-zA-Z_0-9]*/,da:function(a,b){return 0<=gb.indexOf(b[0])},F:!0},{open:/^[a-zA-Z_][a-zA-Z_0-9.]*/,F:!0},{type:"js-number",open:/^[+-]?[0-9.]+/,F:!0},{type:"js-string",open:"'",close:"'",escape:"\\",K:!0},{type:"html-tag",open:/^\s*<\/script/,close:/>/,S:function(a){a.A=null;a.L=null;a.R=kb;return!0}}],lb={open:"{",close:"}"},Y={open:":",
close:";",v:lb},jb=[{type:"css-comment",open:"\x3c!--",close:">"},{type:"css-comment",open:"/*",close:"*/"},{type:"css-string",open:'"',close:'"',escape:"\\",K:!0},{type:"css-number",open:/^[+-]?[0-9.]+[a-zA-Z]*/,F:!0,v:Y},{type:"css-color",open:/^#[0-9a-zA-Z]{3}[0-9a-zA-Z]{0,3}/,F:!0,v:Y},lb,Y,{type:"css-name",open:/^[-.#_a-zA-Z0-9]+/,F:!0,v:lb},{type:"css-attribute-value",open:/^[-a-zA-Z_0-9]+/,F:!0,v:Y},{type:"css-string",open:"'",close:"'",escape:"\\",K:!0},{type:"html-tag",open:/^\s*<\/style/,
close:/>/,S:function(a){a.R=kb;a.A=null;a.L=null;return!0}}],nb=function(a){var b={R:kb,U:null,L:null,A:null},c=[],d=[null],e=[null],f=void 0;a=Ba(a);a.split("\n").forEach(function(l){var g=[],h=0;b.L=b.A;for(var k=0,m=l.length;k<m;k+=p?0:1){var p=!1;if(!f||f.escape!=l.charAt(k)){if(f){var u=f.close?mb(b,f.close,l,k,f.S):0;u&&(k+=u,g.push(new W(l.substring(h,k),f.type||b.A)),h=k,d.pop(),e.pop(),f=e[e.length-1],p=!0)}for(var Ea=0,t;!p&&(t=b.R[Ea]);Ea++)t.v==f&&(u=mb(b,t.open,l,k,t.da))&&(k>h&&t.type!=
d[d.length-1]&&(g.push(new W(l.substring(h,k),d[d.length-1]||b.A)),h=k),k+=u,t.F?(g.push(new W(l.substring(h,k),t.type||b.A)),h=k):(d.push(t.type),e.push(t),f=t),p=!0)}}h<m&&g.push(new W(l.substring(h,m),d[d.length-1]||b.A));c.push(new fb(g,b.L));f&&f.K&&(d.pop(),e.pop(),f=e[e.length-1])});return c},mb=function(a,b,c,d,e){var f;return b.exec&&(f=b.exec(c.substring(d)))?e&&!e(a,f)?0:f[0].length:c.substring(d,d+b.length)==b?b.length:0};var Z,ob=document.location.href;Z=ob instanceof M?ob.clone():new M(ob,void 0);
(function(a,b,c){hb(a,function(d){var e=d.response+"";d=document.getElementById("source");e=nb(e);var f=c||1;F(db===db,"found an incorrect call marker, was an internal function called from the top level?");if($a["tvt.viewsourcetemplates.showSource"])e=$a["tvt.viewsourcetemplates.showSource"]({code:e,ma:b,ka:f,title:a,url:a},void 0);else{for(var l='<div class="header"><h1 id="title">Source: '+Za(a)+"</h1>"+(a?'<a id="view-source" href="view-source:'+V(a)+"\">View Source in Chrome's Source code viewer</a>":
"")+'</div><div class="line-gutter-backdrop"></div><table><tbody>',g=e.length,h=0;h<g;h++){var k=e[h];l+="<tr"+(k.type?' class="'+V(k.type)+'"':"")+'><td class="line-number'+(h+1>=b&&h+1<=b+f?" highlight":"")+'" data-value="'+V(h+1)+'"></td><td class="line-content">';k=k.spans;for(var m=k.length,p=0;p<m;p++){var u=k[p];l+=u.type?'<span class="'+V(u.type)+'">'+Za(u.text)+"</span>":Za(u.text)}l+="</td></tr>"}e=Wa(l+"</tbody></table>")}f=typeof e;if("object"==f&&null!=e||"function"==f)if(e instanceof
T){if(e.Z!==Ta)throw Error("Sanitized content was not of kind HTML.");e=va(new K(J,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value."),e.toString(),e.T)}else G("Soy template output is unsafe for use as HTML: "+e),e=ta("zSoyz");else e=ta(String(e));ya(F(d),e);d=b||0;e=0;f=document;f=f.querySelectorAll&&f.querySelector?f.querySelectorAll("TR"):f.getElementsByTagName("TR");0<=d&&d<f.length&&(e=f[d].offsetTop);window.scrollTo(0,e)})})(Z.j.get("url")||"",parseInt(Z.j.get("line")||
-1,10),parseInt(Z.j.get("count")||0,10));
