(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f=function(a,b){function c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.l=function(d,e,n){for(var p=Array(arguments.length-2),g=2;g<arguments.length;g++)p[g-2]=arguments[g];return b.prototype[e].apply(d,p)}};function h(a){a:{var b=null===a||void 0===a?void 0:a.type;if("string"!==typeof b)b=!1;else switch(b){case "PIPE_MESSAGE":case "DISCONNECT":case "API_INSTALLED":case "WINDOWS_CLOSED":b=!0;break a;default:b=!1}}if(b)a:if(a=null===a||void 0===a?void 0:a.source,"string"!==typeof a)b=!1;else switch(a){case "PAGE":case "EXTENSION":b=!0;break a;default:b=!1}return b};var k={};function l(){if(k!==k)throw Error("Bad secret");};function m(){var a="undefined"!==typeof window?window.trustedTypes:void 0;return null!==a&&void 0!==a?a:null}let q;function r(){var a,b;if(void 0===q)try{q=null!==(b=null===(a=m())||void 0===a?void 0:a.createPolicy("google#safe",{createHTML:c=>c,createScript:c=>c,createScriptURL:c=>c}))&&void 0!==b?b:null}catch(c){q=null}return q};var t=class{};class u extends t{constructor(a){super();l();this.h=a}toString(){return this.h.toString()}}function v(a){var b;const c=null===(b=r())||void 0===b?void 0:b.createScriptURL(a);return new u(null!==c&&void 0!==c?c:a)}function w(a){if(a instanceof u)return a.h;throw Error("Unexpected type when unwrapping TrustedResourceUrl");};var x=class{};class y extends x{constructor(a){super();l();this.j=a}toString(){return this.j}};class z{constructor(a){this.i=a}}const A=new z(a=>0===a.indexOf("chrome-extension://")||0===a.indexOf("moz-extension://")||0===a.indexOf("ms-browser-extension://"));function B(a){var b=C`api/tag_assistant_api_bin.js`;a=a.runtime;var c=a.getURL,d;const e=w(b);b=(null===(d=m())||void 0===d?0:d.isScriptURL(e))?TrustedScriptURL.prototype.toString.apply(e):e;d=c.call(a,b);a:{a=[A];for(c=0;c<a.length;++c)if(b=a[c],b instanceof z&&b.i(d)){a=new y(d);break a}a=void 0}if(!a)throw Error('"'+d+'" is not an extension URL.');return v(d)};function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{const c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}f(D,Error);D.prototype.name="CustomError";var E=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");D.call(this,c+a[d])};f(E,D);E.prototype.name="AssertionError";var F=function(a,b){throw new E("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var H=class{constructor(a,b){this.g=b===G?a:""}};H.prototype.toString=function(){return this.g+""};var G={};/*

 Copyright 2021 The Safevalues Authors
 SPDX-License-Identifier: Apache-2.0
*/
function I(a,b){if(b instanceof t)b=w(b);else if(b instanceof H&&b.constructor===H)b=b.g;else{var c=typeof b;F("expected object of type TrustedResourceUrl, got '"+b+"' of type "+("object"!=c?c:b?Array.isArray(b)?"array":c:"null"));b="type_error:TrustedResourceUrl"}a.src=b;var d;b=(a.ownerDocument&&a.ownerDocument.defaultView||window).document;(d=(c=null===(d=b.querySelector)||void 0===d?void 0:d.call(b,"script[nonce]"))?c.nonce||c.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",d)};function C(a,...b){if(!Array.isArray(a)||!Array.isArray(a.raw))throw new TypeError("trustedResourceUrl is a template literal tag function and can only be called as such (e.g. trustedResourceUrl`/somepath.js`)");if(0===b.length)return v(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var d=c.indexOf("//")+2;var e=c.indexOf("/",d);if(e<=d)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");
d=c.substring(d,e);if(!/^[0-9a-z.:-]+$/i.test(d))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(d))throw Error("Invalid port number.");if(!/(^|\.)[a-z][^.]*$/i.test(d))throw Error("The top-level domain must start with a letter.");d=!0}else d=!1;if(d=!d){if(/^\//.test(c))if("/"===c||1<c.length&&"/"!==c[1]&&"\\"!==c[1])d=!0;else throw Error("The path start in the url is invalid.");else d=!1;d=!d}if(d){if(/^about:blank/.test(c)){if("about:blank"!==c&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");
c=!0}else c=!1;d=!c}if(d)throw Error("Trying to interpolate expressions in an unsupported url format.");c=[a[0]];for(d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return v(c.join(""))};(function(a,b){b.document.documentElement.setAttribute("data-tag-assistant-present",String(Date.now()));const c=b.document.createElement("script");I(c,B(a));b.document.documentElement.appendChild(c);c.remove();let d=void 0;b.document.addEventListener("__TAG_ASSISTANT_API_MESSAGE",e=>{if(h(e.detail)&&(e=e.detail,"PAGE"===e.source))switch(e.type){case "API_INSTALLED":d=a.runtime.connect();d.onDisconnect.addListener(()=>{d=void 0});null===d||void 0===d?void 0:d.onMessage.addListener(n=>{b.document.dispatchEvent(new CustomEvent("__TAG_ASSISTANT_API_MESSAGE",
{detail:n}))});break;case "PIPE_MESSAGE":e.origin=b.origin;null===d||void 0===d?void 0:d.postMessage(e);break;case "DISCONNECT":null===d||void 0===d?void 0:d.disconnect()}})})(chrome,window);}).call(this);
