(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';const m=Array.from("\ud83d\udc35\ud83d\udc21\ud83d\udc36\ud83d\udc28\ud83d\udc38\ud83e\udd8a\ud83d\udc37\ud83d\udc22\ud83d\udc31\ud83d\udc26\ud83d\udc2f\ud83d\udc34\ud83e\udd8b\ud83d\udc2e\ud83d\udc2d\ud83e\udd84\ud83d\udc30\ud83d\udc3c\ud83d\udc24\ud83d\udc39\ud83d\udc32\ud83d\udc1f\ud83e\udd81\ud83d\udc19\ud83e\udd82\ud83e\udd80"),n=Array.from("\ud83d\udd37\ud83d\udfe5\ud83d\udfe1\ud83d\udfe9\ud83d\udd35\u2b55\ud83d\udd36\ud83d\udfe2\ud83d\udfe6\ud83d\udd34\ud83d\udfe8");
n.push(m[Math.floor(Math.random()*m.length)]);
var v=function(b,c){var a,d;const f=null===(d=null===(a=c.sender)||void 0===a?void 0:a.tab)||void 0===d?void 0:d.id;if(null!=f){p("got connection from Tag Assistant on tab %s",f);b.i.tabs.update(f,{autoDiscardable:!1});var g=b.h.get(f);null!=g?g.port=c:(g={port:c,j:new Set},b.h.set(f,g));c.onMessage.addListener(k=>{if("CONTAINER_DETAILS"===k.data.type){const h=k.data.data.nonce,e=b.s.get(h);b.s.delete(h);q(k,e)}else g.j.forEach(h=>{const e=b.g.get(h);e&&("CLEAR_COOKIE"===k.data.type?e.l=!1:e.l||(e.l=
!0,u(b,h)),e.frames.forEach(l=>{q(k,l)}))})});c.onDisconnect.addListener(()=>{p("port to Tag Assistant tab %s closed",f);g.port=void 0})}},y=function(b,c){var a,d,f;const g=null===(d=null===(a=c.sender)||void 0===a?void 0:a.tab)||void 0===d?void 0:d.id,k=null===(f=c.sender)||void 0===f?void 0:f.frameId;p("got connection from tab %s, frame %s",g,k);if(null!=g&&null!=k){b.i.tabs.update(g,{autoDiscardable:!1});var h=b.g.get(g);null==h&&(h=w(void 0),b.g.set(g,h));var e=h.frames.get(k);null!=e?e.port=
c:(e=x(b,c),h.frames.set(k,e));c.onMessage.addListener(l=>{var r,t;null!=h.m&&("CONTAINER_STARTING"===l.data.type&&b.s.set(l.data.data.nonce,e),l.data.emoji=e.emoji,l.source="EXTENSION",null===(t=null===(r=b.h.get(h.m))||void 0===r?void 0:r.port)||void 0===t?void 0:t.postMessage(l))});c.onDisconnect.addListener(()=>{p("port to tab %s, frame %s closed",g,k);e.port=void 0})}},u=function(b,c,a=0){b.i.tabs.executeScript(c,{file:"api/content_script_bin.js",runAt:"document_start",allFrames:!0,frameId:a,
matchAboutBlank:!0},()=>{const d=b.i.runtime.lastError;d&&p("error while injecting Tag Assistant API on tab %s, frame %s, error: %o",c,a,d.message)})},q=function(b,c){null!==c&&void 0!==c&&c.port&&(b.data.emoji=c.emoji,b.source="EXTENSION",c.port.postMessage(b))},w=function(b){return{m:b,frames:new Map,l:!0}},x=function(b,c){c={port:c,emoji:n[b.o]};b.o++;b.o>=n.length&&(b.o=0);return c};function p(...b){console.log(...b)};new class{constructor(){this.i=chrome;this.h=new Map;this.g=new Map;this.o=0;this.s=new Map;this.i.runtime.onConnectExternal.addListener(b=>{"TAG_ASSISTANT_EXTENSION_PORT"===b.name&&v(this,b)});this.i.runtime.onConnect.addListener(b=>{y(this,b)});this.i.webNavigation.onCreatedNavigationTarget.addListener(({tabId:b,sourceTabId:c,url:a})=>{a=new URL(a);a.hostname.endsWith(".google.com")&&null!=a.searchParams.get("restart_tag_assistant")?(this.h.has(c)||((a=this.g.get(c))?(a.m=b,a.l=!0):this.g.set(c,
w(b)),u(this,c),(a=this.h.get(b))?a.j.add(c):this.h.set(b,{j:new Set([c])})),a=!0):a=!1;if(a=!a)a=this.h.get(c),null!==a&&void 0!==a&&a.port?(a.j.add(b),(a=this.g.get(b))?a.m=c:this.g.set(b,w(c)),a=!0):a=!1,a=!a;if(a){var d;(a=this.g.get(c))&&a.l&&(c=this.g.get(b),a=a.m,c?c.m=a:this.g.set(b,w(a)),null!=a&&(null===(d=this.h.get(a))||void 0===d?void 0:d.j.add(b)))}});this.i.tabs.onRemoved.addListener(b=>{var c;p("tab %s removed",b);var a=this.h.get(b);if(a){this.h.delete(b);for(var d of a.j)if(a=this.g.get(d))a.l=
!1}this.g.delete(b);for(const f of this.h.values())f.j.delete(b)&&0===f.j.size&&(d={type:"WINDOWS_CLOSED",source:"PAGE"},null===(c=f.port)||void 0===c?void 0:c.postMessage(d))});this.i.webNavigation.onCommitted.addListener(({tabId:b,frameId:c,url:a})=>{"https://tagassistant.google.com"!==(new URL(a)).origin&&(a=this.g.get(b),(null===a||void 0===a?0:a.l)&&u(this,b,c))});this.i.runtime.onMessageExternal.addListener((b,c,a)=>{a({})})}};}).call(this);
